
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5

development:
 <<: *default
 database: goali_dev
 
test:
 <<: *default
 database: goali_test

production:
 <<: *default
 database: goali
